-------------------------------------------------------------------------------
-- Premade Groups Filter
-------------------------------------------------------------------------------
-- Copyright (C) 2026 Bernhard Saumweber
--
-- This program is free software; you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation; either version 2 of the License, or
-- (at your option) any later version.
--
-- This program is distributed in the hope that it will be useful,
-- but WITHOUT ANY WARRANTY; without even the implied warranty of
-- MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
-- GNU General Public License for more details.
--
-- You should have received a copy of the GNU General Public License along
-- with this program; if not, write to the Free Software Foundation, Inc.,
-- 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
-------------------------------------------------------------------------------

local PGF = select(2, ...)
local L = PGF.L

if GetLocale() ~= "zhCN" then return end

L["addon.name.short"] = "PGF"
L["addon.name.long"] = "Premade Groups Filter"

L["error.syntax"] = "|cffff0000过滤语法错误|r\n\n你的过滤器表达式写法不正确，例如缺少括号，或把 'tanks==1' 写成了 'tanks=1'。\n\n详细错误信息：\n|cffaaaaaa%s|r"
L["error.semantic"] = "|cffff0000过滤语法错误|r\n\n你的过滤器表达式语法不正确，但很可能拼错了变量名，例如把 tanks 写成了 tansk。\n\n详细错误信息：\n|cffaaaaaa%s|r"
L["error.semantic.protected"] = "|cffff0000过滤语法错误|r\n\n关键字 'name' 和 'comment' 已不再支持。请从高级过滤器表达式中移除它们，或点击重置按钮。\n\n自争霸艾泽拉斯前夕起，这些值已受暴雪保护，任何插件都无法再读取。\n\n请使用队伍列表上方的默认搜索栏按队伍名称筛选。\n\n详细错误信息：\n|cffaaaaaa%s|r"
L["message.settingsupgraded"] = "Premade Groups Filter：设置已迁移至版本 %s"
L["message.sortingoverwritten"] = "Premade Groups Filter：默认预创建队伍排序已被插件 %s 覆盖。"
L["message.sortingrestored"] = "Premade Groups Filter：默认预创建队伍排序已由插件 %s 恢复。"
L["message.taint"] = "Premade Groups Filter：插件限制现已生效。队伍查找器已被修改，可能导致 Lua 错误。建议执行 /reload 修复。"

L["dialog.settings"] = GAMEMENU_OPTIONS
L["dialog.reset"] = "重置"
L["dialog.reset.confirm"] = "确认重置所有？"
L["dialog.refresh"] = "搜索"
L["dialog.expl.simple"] = "勾选选项，输入最小值或最大值，然后点击搜索。"
L["dialog.expl.state"] = "队伍需要包含："
L["dialog.expl.min"] = "最小"
L["dialog.expl.max"] = "最大"
L["dialog.expl.advanced"] = "如果以上选项不够用，可以尝试使用高级过滤语法查询。"
L["dialog.normal"] = "普通"
L["dialog.heroic"] = "英雄"
L["dialog.mythic"] = "史诗"
L["dialog.mythicplus"] = "史诗钥石"
L["dialog.to"] = "至"
L["dialog.difficulty"] = "难度 .............................."
L["dialog.members"]    = "队伍人数 .........................."
L["dialog.tanks"]      = "坦克 .............................."
L["dialog.heals"]      = "治疗 .............................."
L["dialog.dps"]        = "输出 .............................."
L["dialog.mprating"]   = "钥石评分 .........................."
L["dialog.pvprating"]  = "PVP评分 ......................."
L["dialog.delvetier"]  = "地下堡层级 ........................."
L["dialog.delvetier.tooltip"] = "部分玩家没有正确设置地下堡层级，只在队伍名称中注明层级。插件无法读取队伍名称，建议配合标准搜索框使用以获得更好结果。"
L["dialog.defeated"]   = "已击败团队首领"
L["dialog.sorting"] = "排序"
L["dialog.usepgf.tooltip"] = "启用或禁用 Premade Groups Filter。"
L["dialog.usepgf.usage"] = "为获得尽可能多的相关结果，请将搜索框与 PGF 搭配使用，因为服务器返回的结果数量有限。"
L["dialog.usepgf.results.server"] = "服务器返回队伍：|cffffffff%d|r"
L["dialog.usepgf.results.removed"] = "被 PGF 隐藏的队伍：|cffffffff%d|r"
L["dialog.usepgf.results.displayed"] = "已显示队伍：|cffffffff%d|r"
L["dialog.tooltip.title"] = "高级过滤语法"
L["dialog.tooltip.variable"] = "变量"
L["dialog.tooltip.description"] = "描述"
L["dialog.tooltip.op.logic"] = "逻辑运算符"
L["dialog.tooltip.op.number"] = "数字运算符"
L["dialog.tooltip.op.string"] = "字符运算符"
L["dialog.tooltip.op.func"] = "函数"
L["dialog.tooltip.example"] = "示例"
L["dialog.tooltip.ilvl"] = "所需物品等级"
L["dialog.tooltip.myilvl"] = "我的物品等级"
L["dialog.tooltip.hlvl"] = "所需荣誉等级"
L["dialog.tooltip.pvprating"] = "队长PvP评分"
L["dialog.tooltip.mprating"] = "队长钥石评分"
L["dialog.tooltip.defeated"] = "已击败的团队首领数量"
L["dialog.tooltip.members"] = "成员数量"
L["dialog.tooltip.tanks"] = "坦克数量"
L["dialog.tooltip.heals"] = "治疗数量"
L["dialog.tooltip.dps"] = "伤害输出数量"
L["dialog.tooltip.partyfit"] = "有适合我职责的位置"
L["dialog.tooltip.classes"] = "指定职业的数量"
L["dialog.tooltip.age"] = "队伍创建时长（分钟）"
L["dialog.tooltip.voice"] = "有语音聊天"
L["dialog.tooltip.myrealm"] = "队长与我同服"
L["dialog.tooltip.noid"] = "我没有锁定进度的副本"
L["dialog.tooltip.matchingid"] = "已击杀首领相同的队伍"
L["dialog.tooltip.seewebsite"] = "查看网站"
L["dialog.tooltip.difficulty"] = "难度"
L["dialog.tooltip.raids"] = "仅选择指定团队副本"
L["dialog.tooltip.dungeons"] = "选择指定地下城"
L["dialog.tooltip.timewalking"] = "选择时光漫游地下城"
L["dialog.tooltip.arena"] = "选择指定竞技场类型"
L["dialog.tooltip.warmode"] = "已启用战争模式"
L["dialog.copy.url.keywords"] = "按 CTRL+C 复制关键字列表链接"
L["dialog.filters.group"] = "队伍"
L["dialog.filters.dungeons"] = "地下城"
L["dialog.filters.delves"] = "地下堡"
L["dialog.filters.advanced"] = "高级过滤语法"
L["dialog.partyfit"] = "职责匹配"
L["dialog.partyfit.tooltip"] = "仅显示仍能容纳你所有队伍成员职责的队伍。独自一人时同样有效。"
L["dialog.notdeclined"] = "过滤已拒绝"
L["dialog.notdeclined.tooltip"] = "隐藏已经拒绝过你的队伍。"
L["dialog.blfit"] = "嗜血匹配"
L["dialog.blfit.tooltip"] = "如果你的队伍中无人能提供嗜血/英勇，则仅显示已拥有嗜血/英勇的队伍，或在你加入后仍有空余 DPS 或治疗位置的队伍。独自一人时同样有效"
L["dialog.brfit"] = "战复匹配"
L["dialog.brfit.tooltip"] = "如果你的队伍中无人能提供战斗复活，则仅显示已拥有战斗复活的队伍，或在你加入后仍有空余位置的队伍。独自一人时同样有效"
L["dialog.matchingid"] = "副本进度匹配"
L["dialog.matchingid.tooltip"] = "仅显示与你副本锁定进度完全相同的队伍。你完全没有锁定进度的队伍始终会显示。"
L["dialog.needsbl"] = "需要嗜血"
L["dialog.needsbl.tooltip"] = "仅显示缺少嗜血/英勇职业的队伍。"
L["dialog.cancelOldestApp"] = "点击后优先取消最早的申请"
L["dialog.button.selectall.title"] = "全"
L["dialog.button.selectall.tooltip"] = "全选"
L["dialog.button.selectnone.title"] = "无"
L["dialog.button.selectnone.tooltip"] = "全不选"
L["dialog.button.selectbountiful.title"] = "丰"
L["dialog.button.selectbountiful.tooltip"] = "选择丰裕地下堡"
L["dialog.button.selectinvert.title"] = "反"
L["dialog.button.selectinvert.tooltip"] = "反选"

L["settings.dialogMovable.title"] = "对话框可移动"
L["settings.dialogMovable.tooltip"] = "允许你用鼠标移动对话框。右键点击可重置位置。"
L["settings.classNamesInTooltip.title"] = "鼠标提示中显示职业"
L["settings.classNamesInTooltip.tooltip"] = "在预创建队伍的鼠标提示中按职责显示职业列表。"
L["settings.coloredGroupTexts.title"] = "彩色队伍名"
L["settings.coloredGroupTexts.tooltip"] = "新创建的队伍名称显示为绿色；如果你之前被拒绝过，则显示为红色。如果你在该副本有锁定进度，活动名称显示为红色。"
L["settings.classBar.title"] = "职业颜色条"
L["settings.classBar.tooltip"] = "在预创建地下城队伍列表中，每个职责下方显示一个小的职业颜色条。"
L["settings.classCircle.title"] = "职业颜色圆环"
L["settings.classCircle.tooltip"] = "在预创建地下城队伍列表中，每个职责背景中显示一个职业颜色圆环。"
L["settings.leaderCrown.title"] = "显示队长"
L["settings.leaderCrown.tooltip"] = "在预创建地下城队伍列表中，队长职责上方显示一个小皇冠。"
L["settings.ratingInfo.title"] = "队长评分"
L["settings.ratingInfo.tooltip"] = "在预创建队伍列表中显示队长的史诗钥石或 PvP 评分。"
L["settings.oneClickSignUp.title"] = "一键申请"
L["settings.oneClickSignUp.tooltip"] = "直接点击队伍即可申请，无需先选中队伍再点击申请。"
L["settings.persistSignUpNote.title"] = "保留申请备注"
L["settings.persistSignUpNote.tooltip"] = "在申请不同队伍时保留“给队长的备注”。默认情况下，选择新队伍时备注会被清空。"
L["settings.signupOnEnter.title"] = "回车申请"
L["settings.signupOnEnter.tooltip"] = "申请加入新队伍时，自动定位到“给队长的留言”文本框，并可按回车确认申请。"
L["settings.skipSignUpDialog.title"] = "跳过申请对话框"
L["settings.skipSignUpDialog.tooltip"] = "尽可能跳过职责和备注提示，直接申请加入队伍。按住 Shift 则始终显示对话框。"
L["settings.specIcon.title"] = "显示专精"
L["settings.specIcon.tooltip"] = "在预创建队伍列表中显示每个成员的职业专精图标。"
L["settings.missingRoles.title"] = "显示缺失职责"
L["settings.missingRoles.tooltip"] = "在预创建队伍列表中显示每个空位的职责图标。"
L["settings.signUpDeclined.title"] = "可申请被拒绝的队伍"
L["settings.signUpDeclined.tooltip"] = "恢复地心之战之前的旧行为，允许申请之前拒绝过你的队伍。"
L["settings.section.mythicplus.title"] = "史诗钥石"
L["settings.section.signup.title"] = "申请"
L["settings.rioRatingColors.title"] = "使用Raider.IO颜色评分"
L["settings.rioRatingColors.tooltip"] = "若已加载Raider.IO插件，则使用Raider.IO评分颜色方案来显示史诗钥石评分。"
L["settings.cancelOldestApp.title"] = "取消最早的申请"
L["settings.cancelOldestApp.tooltip"] = "当待处理申请数量达到上限时，点击任意队伍会先取消你最早的申请，再次点击即可申请。"
L["settings.compactListEntries.title"] = "紧凑列表条目"
L["settings.compactListEntries.tooltip"] = "隐藏游戏风格行，使队伍列表条目占用更少的垂直空间（类似至暗之夜前夕之前的效果）。"
L["settings.groupAge.title"] = "队伍创建时长"
L["settings.groupAge.tooltip"] = "在游戏风格左侧显示队伍的创建时长。不能与紧凑列表条目同时使用。"
L["settings.info.reload"] = "* 更改这些选项，在关闭选项时会自动重载界面。"
L["settings.warning.taint"] = "此选项可能在受限情况下（如团队副本或战斗中）导致 Lua 错误。"

L["dialog.restriction.text"] = "插件限制已生效，过滤可能引发 Lua 错误。"
L["dialog.restriction.ok"] = "仍然过滤"
